### ISSUE TITLE
Recriar a funcionalidade do Computed Field no Drupal 8

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/BaixarHentaiD8#70]
[Dynamic/Virtual field values using computed field property classes](https://www.drupal.org/node/2112677) -> funciona, mas, o ideal é que os valores sejam salvos no banco de dados para não terem que ser reprocessados depois

- [x] Criar um backend que rode antes do salvamento da entidade
- [ ] Criar um gatilho no [Rules](https://www.drupal.org/project/rules) para cada vez que um filho do node for atualizado o pai também ser, isso vai desencadear algumas funções como contagem automática do número de episódios/tamanho 
- [ ]

**Comment by Lucasljj** [comment]
Já que o módulo php foi removido do núcleo... eu deveria fazer um formatador para cada caso específico? (das questãoes que dependem dessa) '-'

**Comment by Lucasljj** [comment]
é... vai ter que ser um formatador para cada caso

**Comment by Lucasljj** [comment]
Isso e as questões filhas dependem de https://www.drupal.org/node/2416765

#31 - pegar o valor do campo "servidor do site" dentro de um formatador e verificar o formato usando algum código php

#32 o mesmo esquema do #31 

#33 fazer uma consulta sql para obter esses valores

**Comment by lucasljj** [comment]
Movido para a #76, já esta quase pronto :)

**Comment by lucasljj** [comment]
Aliás, essa abordagem de formatações é obsoleta, estamos usando alguns hooks para disparar eventos quando o node é salvo/inserido
